import type { InteropScene } from "./export-interop";
import { toAfterEffects } from "./export-interop";

export function generateAeScript(
  scene: InteropScene,
  compWidth: number,
  compHeight: number,
  scale: number,
  includeCamera: boolean,
  includeAnchors: boolean,
): string {
  const { camera, anchors } = toAfterEffects(scene, compWidth, compHeight, scale);
  const lines: string[] = [];

  lines.push("// Generated by Scene It");
  lines.push("// Run this script in After Effects: File > Scripts > Run Script File");
  lines.push("");
  lines.push("(function() {");
  lines.push(`  var comp = app.project.items.addComp("GSV Export", ${compWidth}, ${compHeight}, 1, ${scene.duration.toFixed(2)}, ${scene.fps});`);
  lines.push("");

  if (includeCamera && camera.length > 0) {
    lines.push(`  var cam = comp.layers.addCamera("GSV Camera", [${compWidth / 2}, ${compHeight / 2}]);`);
    lines.push("  cam.autoOrient = AutoOrientType.NO_AUTO_ORIENT;");
    lines.push("");

    const times = camera.map((f) => f.time.toFixed(4));
    const positions = camera.map((f) => `[${f.position.x.toFixed(2)}, ${f.position.y.toFixed(2)}, ${f.position.z.toFixed(2)}]`);
    const orientations = camera.map((f) => `[${f.rotation.pitch.toFixed(3)}, ${f.rotation.yaw.toFixed(3)}, ${f.rotation.roll.toFixed(3)}]`);

    const fovRad = camera[0]?.fov ?? 36;
    const zoom = compHeight / (2 * Math.tan(((fovRad * Math.PI) / 180) / 2));
    lines.push(`  cam.property("Zoom").setValue(${zoom.toFixed(2)});`);

    if (camera.length <= 500) {
      lines.push(`  var camTimes = [${times.join(", ")}];`);
      lines.push(`  var camPos = [${positions.join(", ")}];`);
      lines.push(`  var camOri = [${orientations.join(", ")}];`);
    } else {
      lines.push("  var camTimes = [");
      for (let i = 0; i < times.length; i += 20) {
        lines.push("    " + times.slice(i, i + 20).join(", ") + ",");
      }
      lines.push("  ];");
      lines.push("  var camPos = [");
      for (let i = 0; i < positions.length; i += 10) {
        lines.push("    " + positions.slice(i, i + 10).join(", ") + ",");
      }
      lines.push("  ];");
      lines.push("  var camOri = [");
      for (let i = 0; i < orientations.length; i += 10) {
        lines.push("    " + orientations.slice(i, i + 10).join(", ") + ",");
      }
      lines.push("  ];");
    }

    lines.push(`  cam.property("Position").setValuesAtTimes(camTimes, camPos);`);
    lines.push(`  cam.property("Orientation").setValuesAtTimes(camTimes, camOri);`);
    lines.push("");
  }

  if (includeAnchors && anchors.length > 0) {
    lines.push("  // Anchor null objects");
    for (const a of anchors) {
      const safeName = a.label.replace(/"/g, '\\"');
      lines.push(`  var n = comp.layers.addNull();`);
      lines.push(`  n.threeDLayer = true;`);
      lines.push(`  n.name = "${safeName}";`);
      lines.push(`  n.property("Position").setValue([${a.position.x.toFixed(2)}, ${a.position.y.toFixed(2)}, ${a.position.z.toFixed(2)}]);`);
      lines.push(`  n.property("Orientation").setValue([${a.rotation.x.toFixed(2)}, ${a.rotation.y.toFixed(2)}, ${a.rotation.z.toFixed(2)}]);`);
      lines.push(`  n.property("Scale").setValue([${(a.scale * 100).toFixed(1)}, ${(a.scale * 100).toFixed(1)}, ${(a.scale * 100).toFixed(1)}]);`);

      if (a.appearAt != null) {
        lines.push(`  n.inPoint = ${a.appearAt.toFixed(4)};`);
      }
      if (a.disappearAt != null) {
        lines.push(`  n.outPoint = ${a.disappearAt.toFixed(4)};`);
      }
      lines.push("");
    }
  }

  lines.push(`  alert("GSV scene imported: " + ${camera.length} + " camera frames, " + ${anchors.length} + " anchors.");`);
  lines.push("})();");

  return lines.join("\n");
}
